<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>vantagectl</AssemblyName>
    <RootNamespace>Vantage.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vantage.Core\Vantage.Core.csproj" />
  </ItemGroup>
</Project>
